### ISSUE TITLE
[Proposal] Syntax Sugar Decorators.

### ISSUE THREAD

**Issue by tripodsgames** [pcafstockf/async-injection#8]
Proposal of new decorators.

This decorators are only syntax sugar, they will work with any container.

`@Factory` - Syntax sugar for bindFactory
```typescript
@Factory(factory: SyncFactory<T>)

// Default
@Factory(() => new FactoryExample())
class FactoryExample{}

// Will run the Factory.
container.bindClass(FactoryExample);
```

`@AsyncFactory` - Syntax sugar for bindAsyncFactory
```typescript
@AsyncFactory(factory: AsyncFactory<T>)

// Default
@AsyncFactory(async () => {
    const instance = new FactoryExample();
    await instance.connect();
    return instance;
})
class AsyncFactoryExample{
    connect(): Promise<void> { ... }
}

// Create the bind.
container.bindClass(AsyncFactoryExample);

// Now it's the same as Asynchronous Usage.
```

**Comment by pcafstockf** [comment]
- What context would the decorators operate in?  
- Would this necessitate the addition of a globally declared / named container?
- Is the goal to simply invoke something like `container.bind(ExampleClass)` and have that method look for these decorators to determine which type of binding is desired?


In general, I'm reluctant to expand the API surface, as it could make a library harder to learn.  
(I still kick myself regularly for adding the construction success handler, because in retrospect, that need could have been handled with the existing Factory API).

Adding awareness to a class about the container it is being bound to, also makes me uncomfortable.   
Although clearly it can be worth it ( `@Injectable` and `@PostContruct` for example tie a class to the DI framework).

I've learned this lesson the hard way, because I have cross-platform code that runs inside an Angular app as well as a NodeJS backend and I wanted to use DI with that code.  
Since there are namespace, functionality, framework, and platform collisions between Angular DI and `async-injection`, my cross-platform code cannot reference both frameworks.
Also, Angular DI requires classes to have even more awareness of the container than `async-injection` does.
Ultimately I wrote `@XInjectable`, `@XInject`, etc., decorators which look at the runtime environment and dynamically map to Angular DI or `async-injection` as needed.  But that's [not great either](https://xkcd.com/927/).

`async-injection` obviously does not have a large user base :smile:, but I propose we leave this issue open and see if anyone has thoughts they want to share.

**Comment by tripodsgames** [comment]
>     * Would this necessitate the addition of a globally declared / named container?

>     * What context would the decorators operate in?
> 
>     * Would this necessitate the addition of a globally declared / named container?
> 
>     * Is the goal to simply invoke something like `container.bind(ExampleClass)` and have that method look for these decorators to determine which type of binding is desired?
> 
> 
> In general, I'm reluctant to expand the API surface, as it could make a library harder to learn.
> (I still kick myself regularly for adding the construction success handler, because in retrospect, that need could have been handled with the existing Factory API).
> 
> Adding awareness to a class about the container it is being bound to, also makes me uncomfortable.
> Although clearly it can be worth it ( `@Injectable` and `@PostContruct` for example tie a class to the DI framework).
> 
> I've learned this lesson the hard way, because I have cross-platform code that runs inside an Angular app as well as a NodeJS backend and I wanted to use DI with that code.
> Since there are namespace, functionality, framework, and platform collisions between Angular DI and `async-injection`, my cross-platform code cannot reference both frameworks.
> Also, Angular DI requires classes to have even more awareness of the container than `async-injection` does.
> Ultimately I wrote `@XInjectable`, `@XInject`, etc., decorators which look at the runtime environment and dynamically map to Angular DI or `async-injection` as needed. But that's [not great either](https://xkcd.com/927/).
> 
> `async-injection` obviously does not have a large user base smile, but I propose we leave this issue open and see if anyone has thoughts they want to share.

I like your point of view.
I'll improve the example and reduce the complexity, I didn't make it clear how the factory would work.

**Comment by pcafstockf** [comment]
Going to go ahead and close this.  Feel free to submit a PR if you like.
